---
title: "Data Wrangling for CITES"
author: "Ali Martin and Sarah Lam"
date: "2/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(tmap)
library(here)
```

### Wrangling for Widget 4- Imports and Exports
```{r}
# import data 
wildlife <- read_csv(here("data","cites_wildlife_data.csv")) %>% 
clean_names() %>% 
  filter(year == "2016")
```

```{r}
count <- wildlife %>% 
  count(taxon, sort = TRUE) %>% 
  slice_max(n, n = 10)
  
# i dont know how to make this a data frame so the top imports are:
#"Crocodylus niloticus","Python reticulatus","Alligator mississippiensis","Macaca fascicularis" 
## I sliced it to only show the top 10? Not sure if this is what we want? 

 
```

### filter for top 5 imported species
```{r}
top5 <- wildlife %>% 
  filter(taxon %in% c("Crocodylus niloticus", "Python reticulatus","Alligator mississippiensis","Crocodylus porosus","Varanus salvator")) 
```

## calculate imports and exports of top 5 species

```{r}
top5_imports <- top5 %>% 
  group_by(importer) %>% 
  count(taxon, sort = TRUE) 

top5_exports <- top5 %>% 
  group_by(exporter) %>% 
  count(taxon, sort = TRUE)
  
```

Thinking about changing widget 4, wrangling for this change

```{r}
top_purpose <- wildlife %>% 
  group_by(purpose) %>% 
  summarize(count = n()) %>% 
  slice_max(count, n = 6)

commercial <- wildlife %>% 
  filter(purpose == "T")

ggplot(data = commercial, aes(x = genus)) +
  geom_bar()
```

### Wrangling for Widget 2

Graph of traded species and how much is live or dead

```{r}

```








